version: 2
updates:
  - package-ecosystem: maven
    directory: "/method_logging_aspect"
    schedule:
      interval: weekly
    open-pull-requests-limit: 10
    groups:
      maven-minor-patch:
        update-types: ["minor", "patch"]

  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: weekly
    groups:
      github-actions:
        patterns: ["*"]
